import Foundation

enum AirportDirectory {
    static func name(for airportCode: String) -> String {
        let code = airportCode.uppercased()
        if let mapped = names[code] { return mapped }
        let city = DestinationMetadata.info(for: code).cityName
        return city.uppercased() == code ? code : "\(city) Airport"
    }

    private static let names: [String: String] = [
        "AKL": "Auckland International Airport",
        "AMS": "Amsterdam Airport Schiphol",
        "ARN": "Stockholm-Arlanda Airport",
        "ATH": "Eleftherios Venizelos International Airport",
        "AUH": "Abu Dhabi International Airport",
        "BCN": "Barcelona International Airport",
        "BKK": "Suvarnabhumi Airport",
        "BLR": "Kempegowda International Airport",
        "BNE": "Brisbane International Airport",
        "BOM": "Chhatrapati Shivaji International Airport",
        "BOS": "General Edward Lawrence Logan International Airport",
        "BRU": "Brussels Airport",
        "CAI": "Cairo International Airport",
        "CAN": "Guangzhou Baiyun International Airport",
        "CCU": "Netaji Subhash Chandra Bose International Airport",
        "CDG": "Charles de Gaulle International Airport",
        "CGK": "Soekarno-Hatta International Airport",
        "CHC": "Christchurch International Airport",
        "CMB": "Bandaranaike International Colombo Airport",
        "CNX": "Chiang Mai International Airport",
        "CPH": "Copenhagen Kastrup Airport",
        "CTU": "Chengdu Shuangliu International Airport",
        "DAC": "Hazrat Shahjalal International Airport",
        "DEL": "Indira Gandhi International Airport",
        "DFW": "Dallas Fort Worth International Airport",
        "DOH": "Hamad International Airport",
        "DPS": "Ngurah Rai (Bali) International Airport",
        "DXB": "Dubai International Airport",
        "EWR": "Newark Liberty International Airport",
        "FCO": "Leonardo da Vinci-Fiumicino Airport",
        "FRA": "Frankfurt am Main Airport",
        "FUK": "Fukuoka Airport",
        "HAN": "Noi Bai International Airport",
        "HEL": "Helsinki Vantaa Airport",
        "HKG": "Hong Kong International Airport",
        "HKT": "Phuket International Airport",
        "HND": "Tokyo Haneda International Airport",
        "HYD": "Rajiv Gandhi International Airport",
        "IAH": "George Bush Intercontinental Houston Airport",
        "ICN": "Incheon International Airport",
        "IST": "Istanbul Airport",
        "JED": "King Abdulaziz International Airport",
        "JFK": "John F Kennedy International Airport",
        "JNB": "OR Tambo International Airport",
        "KBV": "Krabi Airport",
        "KIX": "Kansai International Airport",
        "KMG": "Kunming Changshui International Airport",
        "KNO": "Kualanamu International Airport",
        "KTM": "Tribhuvan International Airport",
        "KUL": "Kuala Lumpur International Airport",
        "KWI": "Kuwait International Airport",
        "LAX": "Los Angeles International Airport",
        "LGW": "London Gatwick Airport",
        "LHR": "London Heathrow Airport",
        "MAA": "Chennai International Airport",
        "MAD": "Adolfo Suarez Madrid-Barajas Airport",
        "MAN": "Manchester Airport",
        "MEL": "Melbourne International Airport",
        "MFM": "Macau International Airport",
        "MIA": "Miami International Airport",
        "MNL": "Ninoy Aquino International Airport",
        "MUC": "Munich Airport",
        "MXP": "Malpensa International Airport",
        "NGO": "Chubu Centrair International Airport",
        "NRT": "Narita International Airport",
        "ORD": "Chicago O'Hare International Airport",
        "OSL": "Oslo Lufthavn",
        "PEK": "Beijing Capital International Airport",
        "PEN": "Penang International Airport",
        "PKX": "Beijing Daxing International Airport",
        "PNH": "Phnom Penh International Airport",
        "PUS": "Gimhae International Airport",
        "PVG": "Shanghai Pudong International Airport",
        "RGN": "Yangon International Airport",
        "RUH": "King Khaled International Airport",
        "SEA": "Seattle Tacoma International Airport",
        "SFO": "San Francisco International Airport",
        "SGN": "Tan Son Nhat International Airport",
        "SHA": "Shanghai Hongqiao International Airport",
        "SIN": "Singapore Changi Airport",
        "SYD": "Sydney Kingsford Smith International Airport",
        "SZX": "Shenzhen Bao'an International Airport",
        "TPE": "Taiwan Taoyuan International Airport",
        "USM": "Samui Airport",
        "VIE": "Vienna International Airport",
        "VTE": "Wattay International Airport",
        "WUH": "Wuhan Tianhe International Airport",
        "XIY": "Xi'an Xianyang International Airport",
        "XMN": "Xiamen Gaoqi International Airport",
        "YVR": "Vancouver International Airport",
        "YYZ": "Lester B. Pearson International Airport",
        "ZRH": "Zurich Airport",
    ]
}
